import { useState, useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { usePokemonContext } from '../../context/PokemonContext';
import { generateThemeCSS } from '../../utils/colorExtractor';
import TabSelector from '../ui/TabSelector';
import CodeBlock from '../ui/CodeBlock';

export default function ThemeExport() {
  const { t } = useTranslation();
  const { colors, themeMode } = usePokemonContext();

  const formatTabs = [
    { id: 'tailwind-v4', label: t('export.tailwind4') },
    { id: 'tailwind-v3', label: t('export.tailwind3') },
    { id: 'json', label: t('export.json') },
  ];
  const [format, setFormat] = useState('tailwind-v4');

  const code = useMemo(() => {
    if (!colors?.length) return t('export.empty');

    const css = generateThemeCSS(colors, themeMode);
    const p = colors[0]?.hex || '#395a83';
    const s = colors[1]?.hex || '#5283c5';
    const a = colors[2]?.hex || '#183973';

    const bg = themeMode === 'dark' ? '#14171a' : '#fcfcfd';
    const fg = themeMode === 'dark' ? '#f4f5f6' : '#151e28';
    const card = themeMode === 'dark' ? '#1b2127' : '#ffffff';

    switch (format) {
      case 'tailwind-v4':
        return `/* Pokemon theme - generated by Pokémon Palette */

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);
  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);
  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);
  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);
  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);
  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);
  --color-destructive: var(--destructive);
  --color-destructive-foreground: var(--destructive-foreground);
  --color-border: var(--border);
  --color-input: var(--input);
  --color-ring: var(--ring);
  --color-chart-1: var(--chart-1);
  --color-chart-2: var(--chart-2);
  --color-chart-3: var(--chart-3);
  --color-chart-4: var(--chart-4);
  --color-chart-5: var(--chart-5);
  --color-sidebar: var(--sidebar);
  --color-sidebar-foreground: var(--sidebar-foreground);
  --color-sidebar-primary: var(--sidebar-primary);
  --color-sidebar-primary-foreground: var(--sidebar-primary-foreground);
  --color-sidebar-accent: var(--sidebar-accent);
  --color-sidebar-accent-foreground: var(--sidebar-accent-foreground);
  --color-sidebar-border: var(--sidebar-border);
  --color-sidebar-ring: var(--sidebar-ring);
}

:root {
  --background: ${bg};
  --foreground: ${fg};
  --card: ${card};
  --card-foreground: ${fg};
  --popover: ${card};
  --popover-foreground: ${fg};
  --primary: ${p};
  --primary-foreground: #ffffff;
  --secondary: ${s};
  --secondary-foreground: #ffffff;
  --muted: ${themeMode === 'dark' ? '#252d37' : '#f2f4f7'};
  --muted-foreground: ${themeMode === 'dark' ? '#98a4b3' : '#627084'};
  --accent: ${a};
  --accent-foreground: #ffffff;
  --destructive: #ef4444;
  --destructive-foreground: #ffffff;
  --border: ${themeMode === 'dark' ? '#2d3743' : '#e0e5eb'};
  --input: ${themeMode === 'dark' ? '#2d3743' : '#e0e5eb'};
  --ring: ${p};
  --chart-1: ${p};
  --chart-2: ${s};
  --chart-3: ${a};
  --chart-4: ${p};
  --chart-5: ${s};
  --sidebar: ${card};
  --sidebar-foreground: ${fg};
  --sidebar-primary: ${p};
  --sidebar-primary-foreground: #ffffff;
  --sidebar-accent: ${themeMode === 'dark' ? '#252d37' : '#f2f4f7'};
  --sidebar-accent-foreground: ${fg};
  --sidebar-border: ${themeMode === 'dark' ? '#2d3743' : '#e0e5eb'};
  --sidebar-ring: ${p};
}`;
      case 'tailwind-v3':
        return `// tailwind.config.js
module.exports = {
  theme: {
    extend: {
      colors: {
        background: '${bg}',
        foreground: '${fg}',
        primary: {
          DEFAULT: '${p}',
          foreground: '#ffffff',
        },
        secondary: {
          DEFAULT: '${s}',
          foreground: '#ffffff',
        },
        accent: {
          DEFAULT: '${a}',
          foreground: '#ffffff',
        },
        muted: {
          DEFAULT: '${themeMode === 'dark' ? '#252d37' : '#f2f4f7'}',
          foreground: '${themeMode === 'dark' ? '#98a4b3' : '#627084'}',
        },
        card: {
          DEFAULT: '${card}',
          foreground: '${fg}',
        },
        border: '${themeMode === 'dark' ? '#2d3743' : '#e0e5eb'}',
      },
    },
  },
};`;
      case 'json':
        return JSON.stringify({
          background: bg,
          foreground: fg,
          primary: p,
          secondary: s,
          accent: a,
          muted: themeMode === 'dark' ? '#252d37' : '#f2f4f7',
          'muted-foreground': themeMode === 'dark' ? '#98a4b3' : '#627084',
          card: card,
          border: themeMode === 'dark' ? '#2d3743' : '#e0e5eb',
        }, null, 2);
      default:
        return css;
    }
  }, [colors, themeMode, format]);

  return (
    <section className="rounded-xl border overflow-hidden" style={{ background: 'var(--card)', borderColor: 'var(--border)' }}>
      <div className="p-6 pb-0">
        <h2 className="text-base font-semibold mb-1" style={{ color: 'var(--foreground)' }}>
          Export Theme
        </h2>
        <TabSelector tabs={formatTabs} active={format} onChange={setFormat} className="mb-4" />
      </div>
      <div className="px-6 pb-6">
        <CodeBlock code={code} language={formatTabs.find(t => t.id === format)?.label || 'CSS'} />
      </div>
    </section>
  );
}
